//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfServiceLibrary1
{
    using System;
    using System.Collections.Generic;
    using System.Runtime.Serialization;

    [DataContract(Name = "Review")]
    public partial class ReviewModel
    {
        [DataMember]
        public int Id { get; set; }
        [DataMember]
        public string Reviewer { get; set; }
        [DataMember]
        public string Summary { get; set; }
        [DataMember]
        public decimal Rating { get; set; }
        [DataMember]
        public string ReviewText { get; set; }
        [DataMember]
        public Nullable<int> Movie_Id { get; set; }
        [DataMember]
        public virtual MovieModel MovieModel { get; set; }
    }
}
